In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [3]:
data = pd.read_csv("spambase.data")

In [4]:
data.head()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278,1
0,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
1,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
2,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,1.85,0.00,0.00,1.85,0.00,0.00,...,0.00,0.223,0.0,0.000,0.000,0.000,3.000,15,54,1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 58 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       4600 non-null   float64
 1   0.64    4600 non-null   float64
 2   0.64.1  4600 non-null   float64
 3   0.1     4600 non-null   float64
 4   0.32    4600 non-null   float64
 5   0.2     4600 non-null   float64
 6   0.3     4600 non-null   float64
 7   0.4     4600 non-null   float64
 8   0.5     4600 non-null   float64
 9   0.6     4600 non-null   float64
 10  0.7     4600 non-null   float64
 11  0.64.2  4600 non-null   float64
 12  0.8     4600 non-null   float64
 13  0.9     4600 non-null   float64
 14  0.10    4600 non-null   float64
 15  0.32.1  4600 non-null   float64
 16  0.11    4600 non-null   float64
 17  1.29    4600 non-null   float64
 18  1.93    4600 non-null   float64
 19  0.12    4600 non-null   float64
 20  0.96    4600 non-null   float64
 21  0.13    4600 non-null   float64
 22  0.14    4600 non-null   float64
 23  0.15    4600 non-null   float64
 24  0.16    4600 non-null   float64
 25  0.17    4600 non-null   float64
 26  0.18    4600 non-null   float64
 27  0.19    4600 non-null   float64
 28  0.20    4600 non-null   float64
 29  0.21    4600 non-null   float64
 30  0.22    4600 non-null   float64
 31  0.23    4600 non-null   float64
 32  0.24    4600 non-null   float64
 33  0.25    4600 non-null   float64
 34  0.26    4600 non-null   float64
 35  0.27    4600 non-null   float64
 36  0.28    4600 non-null   float64
 37  0.29    4600 non-null   float64
 38  0.30    4600 non-null   float64
 39  0.31    4600 non-null   float64
 40  0.33    4600 non-null   float64
 41  0.34    4600 non-null   float64
 42  0.35    4600 non-null   float64
 43  0.36    4600 non-null   float64
 44  0.37    4600 non-null   float64
 45  0.38    4600 non-null   float64
 46  0.39    4600 non-null   float64
 47  0.40    4600 non-null   float64
 48  0.41    4600 non-null   float64
 49  0.42    4600 non-null   float64
 50  0.43    4600 non-null   float64
 51  0.778   4600 non-null   float64
 52  0.44    4600 non-null   float64
 53  0.45    4600 non-null   float64
 54  3.756   4600 non-null   float64
 55  61      4600 non-null   int64
 56  278     4600 non-null   int64
 57  1       4600 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

In [6]:
data.describe()

,0,0.64,0.64.1,0.1,0.32,0.2,0.3,0.4,0.5,0.6,...,0.41,0.42,0.43,0.778,0.44,0.45,3.756,61,278,1
count,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,...,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,0.104576,0.212922,0.280578,0.065439,0.312222,0.095922,0.114233,0.105317,0.090087,0.239465,...,0.038583,0.139061,0.016980,0.268960,0.075827,0.044248,5.191827,52.170870,283.290435,0.393913
std,0.305387,1.290700,0.504170,1.395303,0.672586,0.273850,0.391480,0.401112,0.278643,0.644816,...,0.243497,0.270377,0.109406,0.815726,0.245906,0.429388,31.732891,194.912453,606.413764,0.488669
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.588000,6.000000,35.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.065000,0.000000,0.000000,0.000000,0.000000,2.275500,15.000000,95.000000,0.000000
75%,0.000000,0.000000,0.420000,0.000000,0.382500,0.000000,0.000000,0.000000,0.000000,0.160000,...,0.000000,0.188000,0.000000,0.314250,0.052000,0.000000,3.705250,43.000000,265.250000,1.000000
max,4.540000,14.280000,5.100000,42.810000,10.000000,5.880000,7.270000,11.110000,5.260000,18.180000,...,4.385000,9.752000,4.081000,32.478000,6.003000,19.829000,1102.500000,9989.000000,15841.000000,1.000000

In [7]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [10]:
class_distribution = y.value_counts(normalize=True)
class_distribution

1
0    0.606087
1    0.393913
Name: proportion, dtype: float64

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

In [12]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [19]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [0.01, 0.1, 1, 10, 100], 'penalty': ['l1', 'l2']}

grid_search = GridSearchCV(
    LogisticRegression(random_state=42, max_iter=500, solver='liblinear'),
    param_grid, scoring='f1', cv=5
)

In [20]:
grid_search.fit(X_train_scaled, y_train)
best_model = grid_search.best_estimator_

In [22]:
y_pred = best_model.predict(X_test_scaled)

In [23]:
grid_search.best_params_

{'C': 10, 'penalty': 'l1'}

In [26]:
from sklearn.metrics import classification_report, ConfusionMatrixDisplay

y_pred = grid_search.best_estimator_.predict(X_test_scaled)
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.94      0.95      0.94       836\n           1       0.92      0.90      0.91       544\n\n    accuracy                           0.93      1380\n   macro avg       0.93      0.93      0.93      1380\nweighted avg       0.93      0.93      0.93      1380\n'

In [28]:
grid_search.best_params_

{'C': 10, 'penalty': 'l1'}

In [29]:
grid_search.best_params_

{'C': 10, 'penalty': 'l1'}

In [30]:
grid_search.best_score_

0.9028430614597923